<?php
/**
 * Contao
 * German translation file
 *
 * copyright  Tim Gatzky 2012
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['pdf_hide'] = array('In PDF verstecken','Wählen Sie hier um dieses Feld nicht im PDF zu rendern.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['form_pdf_legend'] = 'PDF Einstellungen';