<?php
/**
 * Contao
 * German translation file
 *
 * copyright  Tim Gatzky 2012
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form']['form_pdf']					= array('PDF generieren','Wählen Sie hier um ein PDF aus den Formulardaten zu erstellen.');
$GLOBALS['TL_LANG']['tl_form']['form_pdf_template']			= array('HTML-Template-Vorlage wählen','Bitte wählen Sie die HTML-Vorlage aus.');
$GLOBALS['TL_LANG']['tl_form']['form_pdf_attachment']		= array('Als Anhang versenden','Wählen Sie hier wenn das PDF-Dokument als Anlage versendet werden soll.');
$GLOBALS['TL_LANG']['tl_form']['form_pdf_plugin']			= array('PDF Plugin','Bitte wählen Sie das Plugin, das zu Erstellung des PDFs verwendet werden soll.');
$GLOBALS['TL_LANG']['tl_form']['form_pdf_plugin']['tcpdf'] 	= array('TCPDF');
$GLOBALS['TL_LANG']['tl_form']['form_pdf_plugin']['dompdf'] = array('DOMPDF');
$GLOBALS['TL_LANG']['tl_form']['form_pdf_paper'] 			= array('Blattformat','Bitte wählen Sie das Format. Weiter Formate können über die Globale: $GLOBALS["FORM_PDF"]["papers"] ergänzt werden.');
